FT:
  app:
    dice:
      title: Dice Roller
      label:
        formula: Dice Formula
        minimum: Min Damage
        multiplier: Multiplier
      action:
        submit: Roll
        cancel: Cancel
  dialog:
    damage:
      title: Apply {damage} Damage to {name}
      label:
        stops: Stops {hits}
