FT:
  app:
    dice:
      title: Dice Roller
      label:
        formula: Dice Formula
        multiplier: Multiplier
  dialog:
    damage:
      title: Apply {damage} Damage to {name}
      label:
        stops: Stops {hits}
